// Developed by IPAM - dhemerson.costa@ipam.org.br // 
// This step performs a selection of pixels with a high probability to be wetlands in Cerrado
// For this, we applied the following spatio-temporal filters:
// i) Monthly frequency of water detection from 1985 to 2020 (generated by step 2) - derived from GT Água BETA (without filters)
// ii) Mapbiomas class = stable classes of grassland or savana
// iii) HAND < 15m - Planforms layer (filter only to terrain with water probability)
// iv) SLOPE < 10 slope - avoid false-positives (ALOS/AW3D30)
// v) Reference data SEMA/SP and SEMA/MG

// Reference wetlands data were used (Inventário Florestal - SIMA/SP):
// **DESCREVER O QUE FOI FEITO EM SP

// Definir parametros 
var limiar_min = 3;    // 1-420
var limiar_max = 100;  // 1-420
var limiar_slope = 10; // 1-100

// parametros de exportação 
var dirout = 'projects/mapbiomas-workspace/AUXILIAR/CERRADO/c6-wetlands/input_masks/';

////////////////////////////////////////////////////////////////////////////////
// importar assets
/// limites do cerrado
var biomas = ee.Image('projects/mapbiomas-workspace/AUXILIAR/biomas-2019-raster');
var cerrado = biomas.updateMask(biomas.eq(4)); 
/// frequencia de agua (sem correção) - beta do GT Água
var freq_85_19 = ee.Image('projects/mapbiomas-workspace/AUXILIAR/CERRADO/c6-wetlands/input_masks/waterFreq_CERRADO_1985_2019')
                .updateMask(cerrado);
/// limites dos estados
var assetStates = ee.Image('projects/mapbiomas-workspace/AUXILIAR/estados-2016-raster');
///               
/// produto mapbiomas - coleção 5 
//var mapbiomas = ee.Image('projects/mapbiomas-workspace/public/collection5/mapbiomas_collection50_integration_v1')
//                .select(['classification_' + ano], [ano])
//                .updateMask(cerrado);
                
/// classes estáveis coleção 5 
var mapbiomas = ee.Image('projects/mapbiomas-workspace/AUXILIAR/CERRADO/c6-wetlands/input_masks/stablePixels_C5');
///                
///  modelo digital de superfície
var SLOPE = ee.Terrain.slope(ee.Image('JAXA/ALOS/AW3D30_V1_1')
                .select('AVE')
                .updateMask(cerrado));
///              
/// mascara de HAND
var HAND = ee.Image('projects/mapbiomas-workspace/AUXILIAR/CERRADO/c6-wetlands/input_masks/aoi_wetlands_c6')
           .updateMask(cerrado);
           
// dados de referencia SEMA/SP (Inventário Florestal de SP)
var SEMA_SP = ee.Image('projects/mapbiomas-workspace/VALIDACAO/MATA_ATLANTICA/SP_IF_2020_2');
SEMA_SP = SEMA_SP.remap(
                  [3, 4, 5,  9, 11,12,13,15,18,19,20,21,22,23,24,25,26,29,30,31,32,33],
                  [3, 4, 3, 21, 11, 12,12,15,19,19,19,19,25,25,25,25,33,25,25,25,25,33]);
// binarizar apenas area umida
var SEMA_bin = SEMA_SP.remap(
                  [3, 4, 5, 9, 11, 12, 13, 15, 18,19,20,21,22,23,24,25,26,29,30,31,32,33],
                  [0, 0, 0, 0,  1,  0, 0, 0,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
                  var SEMA_bin = SEMA_bin.unmask(0).updateMask(assetStates.eq(35));
                  
///
// definir palheta
var palettes = require('users/mapbiomas/modules:Palettes.js');
var vis = {
    'min': 0,
    'max': 34,
    'palette': palettes.get('classification2')
};
//
// plotar
/// produto Mapbiomas
Map.addLayer(mapbiomas, vis, "Amostras estáveis C5 ", false);
/// produto de frequência de água
Map.addLayer(freq_85_19, {palette: ["#6CFF0B", "#326213", "#F7EF05", "#F07108", "#FB0303", "#B20D8A"],
                          min:1, max:420}, "Frequência Água 1985-2019", false);
//         
// filtrar o produto de agua apenas que ocorre em pastagem
var pasture = freq_85_19.updateMask(mapbiomas.eq(15));
// filtrar o produto de agua apenas que ocorre na fisionomia de campo
var grassland = freq_85_19.updateMask(mapbiomas.eq(12));
// filtrar o produto de agua apenas que ocorre na fisionomia de savana
var savana = freq_85_19.updateMask(mapbiomas.eq(4));
//                         
// histograma de classes mapeadas como água em algum momento da série
var freq_classes = mapbiomas.updateMask(freq_85_19);
//var histogram_classes = ui.Chart.image.histogram({image: freq_classes,
//                                                  maxPixels: 26112495766});
//  histogram_classes.setOptions({
//  title: 'Classes mapeadas como água pelo menos uma vez - ' + ano,
//});
//print (histogram_classes);
//
// histograma de frequências em campo
var histogram_grassland = ui.Chart.image.histogram({image: grassland,
                                                  maxPixels: 26112495766});
  histogram_grassland.setOptions({
  title: 'Frequências Campo',
});
print (histogram_grassland);
//
// histograma de frequências em savana
var histogram_savana = ui.Chart.image.histogram({image: savana,
                                                  maxPixels: 26112495766});
  histogram_savana.setOptions({
  title: 'Frequências Savana',
  });
  print (histogram_savana);

// histograma de frequências em pastagem
var histogram_pasture = ui.Chart.image.histogram({image: pasture,
                                                  maxPixels: 26112495766});
  histogram_pasture.setOptions({
  title: 'Frequências Pasto',
});
print (histogram_pasture);
//
// Filtrar frequências
var filtered_freq_pasture = pasture.updateMask(freq_85_19.gt(limiar_min).and(freq_85_19.lt(limiar_max)));
var filtered_freq_grassland = grassland.updateMask(freq_85_19.gt(limiar_min).and(freq_85_19.lt(limiar_max)));
var filtered_freq_savana = savana.updateMask(freq_85_19.gt(limiar_min).and(freq_85_19.lt(limiar_max)));
///
// Plotar
//Map.addLayer(filtered_freq_grassland, {palette: ["#6CFF0B", "#326213", "#F7EF05", "#F07108", "#FB0303", "#B20D8A"],
//                                       min:1, max:420}, "Filtro freq. Grassland " + ano, false); 
///                         
//Map.addLayer(filtered_freq_savana, {palette: ["#6CFF0B", "#326213", "#F7EF05", "#F07108", "#FB0303", "#B20D8A"],
//                          min:1, max:420}, "Filtro freq. Savana " + ano, false); 
///                          
//Map.addLayer(SLOPE.updateMask(SLOPE.gt(limiar_slope)), {palette: ["red"], min:0, max:100}, "Slope ALOS");
Map.addLayer(SLOPE, {palette: ["purple", "blue", "green", "yellow", "orange", "red" ], min:1, max:15}, "Slope ALOS", false);
//
//
// filtrar por terreno
var pasture_hand_slope = filtered_freq_pasture.updateMask(HAND.eq(1).and(SLOPE.lt(limiar_slope)));
var grassland_hand_slope = filtered_freq_grassland.updateMask(HAND.eq(1).and(SLOPE.lt(limiar_slope)));
var savana_hand_slope = filtered_freq_savana.updateMask(HAND.eq(1).and(SLOPE.lt(limiar_slope)));
//
// blend fisionomias (nao considerar pasto)
var potential_wetland = savana_hand_slope.blend(grassland_hand_slope);
//var potential_wetland = potential_wetland.blend(pasture_hand_slope);

//plotar
//Map.addLayer(grassland_hand_slope, {palette:['blue'], min:1, max:420}, "Grassland +Terrain")
//Map.addLayer(savana_hand_slope, {palette:['blue'], min:1, max:420}, "Savana +Terrain")
Map.addLayer(SEMA_SP, vis, "SEMA/SP", false);
/// plotar AOI
Map.addLayer(HAND, {palette:['white', 'red', 'yellow'], min:0, max:2}, "AOI", false);

// CORRIGIR amostras para o estado de SP
// Wetlands do IF recortadas para AOI
var sema_mask = SEMA_bin.updateMask(HAND);

Map.addLayer(sema_mask, vis, 'SEMA MASK');
// apagar as areas umidas potenciais no estado de sao paulo
var potential_wetland2 = potential_wetland.updateMask(assetStates.neq(35));
// atualizar o estado de são paulo com as áreas umidas potenciais baseadas no inventário 
var potential_wetland2 = potential_wetland2.blend(sema_mask);
var potential_wetland2 = potential_wetland2.updateMask(potential_wetland2.gt(0));
// apagar o que ocorrer em classe de água ou pasto no mapbiomas
//var potential_wetland2 = potential_wetland2.updateMask(mapbiomas.eq(4).or(mapbiomas.eq(12)));
//var potential_wetland2 = potential_wetland2.updateMask(mapbiomas.neq(33));
//var potential_wetland2 = potential_wetland2.updateMask(mapbiomas.neq(15)); // id do pasto

// reclassificar máscara (maior que 0 = potencial area umida)
var train_wetland = ee.Image(0)
                    .where(potential_wetland2.eq(0), 0)   // não AU
                    .where(potential_wetland2.gt(0).and(potential_wetland2.lt(421)), 1)   // AU
                    .updateMask(potential_wetland2);


// remap potential wetland to wetland class
var train_wetland = train_wetland.remap([0, 1],
                                        [0, 11]);
                                        
// merge stable samples with wetlands
var train_wetland = mapbiomas.blend(train_wetland);

// plot
Map.addLayer(train_wetland, vis, "Training Mask");


// Exportar para asset
Export.image.toAsset({
    "image": train_wetland.toInt8(),
    "description": 'trainingMask_wetlands_c6',
    "assetId": dirout + 'trainingMask_wetlands_c6',
    "scale": 30,
    "pyramidingPolicy": {
        '.default': 'mode'
    },
    "maxPixels": 1e13,
    "region": train_wetland
});  
