// merge filtered samples generated by 'carta' in the step 4 and consolidate into a single asset
// dhemerson.costa@ipam.org.br

// path of samples
var root = 'users/dh-conciani/collection7/sample/filtered_points/byCarta/';
var output =  'users/dh-conciani/collection7/sample/filtered_points/consolidated/';

// define version of points to consolidate
var version = '3';

// import cerrado feature
var cerrado = ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/biomas-2019')
                .filterMetadata('Bioma', 'equals', 'Cerrado');

// import ibge carta's and filter to cerrado
var cartas = ee.FeatureCollection('projects/mapbiomas-workspace/AUXILIAR/cartas')
              .filterBounds(cerrado);
              
// extract basenames
var basenames = cartas.aggregate_array('grid_name')
                    .remove('SG-21-X-B')
                    .getInfo();
                    
// create empty recipe 
var recipe = ee.FeatureCollection([]);

// for each carta
basenames.forEach(function(file_i) {
  // build filename 
  var filename_i = file_i + '_v' + version;
  // read points for the filename [i]
  var samples_i = ee.FeatureCollection(root + filename_i);
  // merge into recipe
  recipe = recipe.merge(samples_i);
});


// export as GEE asset
Export.table.toAsset(recipe,
  'samplePoints_filtered_v' + version,
  output + 'samplePoints_filtered_v' + version);
