// -- -- -- -- 11_spatial
// spatial filter - minimum area
// barbara.silva@ipam.org.br

// define root
var root = 'projects/mapbiomas-workspace/COLECAO_DEV/COLECAO8_DEV/';

// define input file 
var file_in = 'CERRADO_col8_gapfill_incidence_temporal_frequency_geomorphology_v14';

// define output version 
var version_out = 14;

// read image
var classification = ee.Image(root + file_in);

// define minimum mapeable area
var filter_size = 6;

// import mapbiomas color ramp
var vis = {
      min:0,
      max:62,
      palette: require('users/mapbiomas/modules:Palettes.js').get('classification7'),
    };

// plot  input version
Map.addLayer(classification.select(['classification_2010']), vis, 'input 2010');

// create an empty container
var filtered = ee.Image([]);

// apply filter
ee.List.sequence({'start': 1985, 'end': 2022}).getInfo()
      .forEach(function(year_i) {
        // compute the focal model
        var focal_mode = classification.select(['classification_' + year_i])
                .unmask(0)
                .focal_mode({'radius': 1, 'kernelType': 'square', 'units': 'pixels'});
 
        // compute te number of connections
        var connections = classification.select(['classification_' + year_i])
                .unmask(0)
                .connectedPixelCount({'maxSize': 100, 'eightConnected': false});
        
        // get the focal model when the number of connections of same class is lower than parameter
        var to_mask = focal_mode.updateMask(connections.lte(filter_size));

        // apply filter
        var classification_i = classification.select(['classification_' + year_i])
                .blend(to_mask)
                .reproject('EPSG:4326', null, 30);

        // stack into container
        filtered = filtered.addBands(classification_i.updateMask(classification_i.neq(0)));
        }
      );

// print filtered
Map.addLayer(filtered.select(['classification_2010']), vis, 'filtered 2010 - round 1');

// set container 
var container = ee.Image([]);

// apply filter
ee.List.sequence({'start': 1985, 'end': 2022}).getInfo()
      .forEach(function(year_i) {
        // compute the focal model
        var focal_mode = filtered.select(['classification_' + year_i])
                .unmask(0)
                .focal_mode({'radius': 1, 'kernelType': 'square', 'units': 'pixels'});
 
        // compute te number of connections
        var connections = filtered.select(['classification_' + year_i])
                .unmask(0)
                .connectedPixelCount({'maxSize': 100, 'eightConnected': false});
        
        // get the focal model when the number of connections of same class is lower than parameter
        var to_mask = focal_mode.updateMask(connections.lte(filter_size));

        // apply filter
        var classification_i = filtered.select(['classification_' + year_i])
                .blend(to_mask)
                .reproject('EPSG:4326', null, 30);

        // stack into container
        container = container.addBands(classification_i.updateMask(classification_i.neq(0)));
        }
      );

Map.addLayer(container.select(['classification_2010']), vis, 'filtered 2010 - round 2');

// create container 
var container2 = ee.Image([]);

// fill zeros (blank spaces generated by regions register)
ee.List.sequence({'start': 1985, 'end': 2022}).getInfo()
  .forEach(function(year_i) {
    // compute the focal mode with an extended kernel
    var focal_mode =  container.select(['classification_' + year_i])
                .unmask(0)
                .focal_mode({'radius': 4, 'kernelType': 'square', 'units': 'pixels'});
                
    // get only blank pixels (value equals to zero) 
    var to_mask = focal_mode.updateMask(container.select(['classification_2010']).unmask(0).eq(0));
    
    // apply filter
    var classification_i = container.select(['classification_' + '2010'])
                .blend(to_mask)
                .reproject('EPSG:4326', null, 30);
    
    // stack into container
    container2 = container2.addBands(classification_i.updateMask(classification_i.neq(0)));
  });

Map.addLayer(container2.select(['classification_2010']), vis, 'final filled');
print ('output', container)
// export as GEE asset
Export.image.toAsset({
    'image': container,
    'description': 'CERRADO_col8_gapfill_incidence_temporal_frequency_geomorphology_spatial_v' + version_out,
    'assetId': root + 'CERRADO_col8_gapfill_incidence_temporal_frequency_geomorphology_spatial_v' + version_out,
    'pyramidingPolicy': {
        '.default': 'mode'
    },
    'region': classification.geometry(),
    'scale': 30,
    'maxPixels': 1e13
});
